topcoder-platform/taas-es-processor

src/bootstrap.js
The change are mentioned on https://github.com/topcoder-platform/taas-apis/issues/54
=> allow job candidate to be cancelled

src/scripts/createIndex.js, src/services/JobCandidateProcessorService.js
- update es mapping
- update Joi schemas
=> handle externalId and resume fields for JobCandidate

src/services/JobCandidateProcessorService.js, src/services/JobProcessorService.js, src/services/ResourceBookingProcessorService.js
Note that update/create operations share same schema now.
=> Update joi schemas to allow null values

src/scripts/createIndex.js
=> add duration to ES mapping for job

src/bootstrap.js
feat: support "interview" job candidate status
Support for https://github.com/topcoder-platform/taas-app/issues/114
=> [PROD] [HOTFIX] Post Release Patch 1.0.1

src/bootstrap.js, src/scripts/createIndex.js, src/services/JobProcessorService.js
- feat: Add new field `isApplicationPageActive` to the Job model https://github.com/topcoder-platform/taas-apis/issues/168
=> [PROD] Post Release Patch 1.5.1

src/bootstrap.js, test/unit/test.js
feat: add JC status "topcoder-rejected"
=> [DEV] Patch 1.5.3.1, part 2

src/scripts/createIndex.js
using lowercase normalizer to be able to sort by string fields
=> fix: resource booking search issues

src/scripts/createIndex.js
use the same role index mapping with https://github.com/topcoder-platform/taas-apis/pull/299
@nikolay83
=> fix: role index use normalizer

src/services/WorkPeriodProcessorService.js
=> Update WorkPeriodProcessorService.js - add key

src/services/RoleProcessorService.js
=> fix: taas-apis issue #365

src/scripts/createIndex.js, src/services/JobCandidateProcessorService.js, src/services/JobProcessorService.js, src/services/ResourceBookingProcessorService.js, src/services/WorkPeriodProcessorService.js
=> Send Weekly Surveys

src/scripts/createIndex.js, src/services/JobCandidateProcessorService.js
=> resolve: topcoder-platform/taas-apis#475

.circleci/config.yml, src/bootstrap.js
Fix issue: https://github.com/topcoder-platform/taas-es-processor/issues/116
=> Support 'Did not Post' status on rcrmStatus field

src/services/JobProcessorService.js
https://topcoder.atlassian.net/browse/TSJR-222
=> Update JobProcessorService.js to skills structure

.circleci/config.yml
=> PROD - Skills release

config/default.js, package-lock.json, package.json, src/services/JobProcessorService.js, src/services/RCRMService.js
https://topcoder.atlassian.net/browse/TSJR-243
=> direct RCRM access instead of zapier

src/services/RCRMService.js
https://topcoder.atlassian.net/browse/CORE-88?focusedCommentId=65219&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-65219
=> CORE-88 fix job external ids -> master

src/services/RCRMService.js
https://topcoder.atlassian.net/browse/CORE-88
=> CORE-88 fix taas API calls to patch jobs -> master

.circleci/config.yml, docker/Dockerfile, package-lock.json, package.json
https://topcoder.atlassian.net/browse/CORE-385
=> CORE-385 Reduce taas-es-processor critical vulnerabilities -> master
